package org.vcgdev.supportctxbot

import kie.MessageResponse;
import kie.ProcessIntention
import kie.Customer;
import kie.TicketCreated;
import kie.CommentCreated;
declare MainNode
  number:int
  end
rule "The intention is a single ask"
    when $a:ProcessIntention(intention().intentType()=="ask")
    then
        $a.findAnswer();
     end
//from here the bot havre to navigate in the ontology to get responses
rule "The intention is an entity"
    when $a:ProcessIntention(intention().intentType()=="entity")
    then
       $a.setAnswer("Por favor ingresa una breve descripcion del problema");
       $a.searchMainNode();
       //detect nunmber of nodes
       MainNode main = new MainNode();
       main.setNumber($a.mainNodes().size());
       insert(main);
     end
rule "Main nodes is empty"
    when $b:MainNode(number==0)
        $a:ProcessIntention(intention().intentType()=="entity")
    then
      $a.setAnswer("No se encontro ninguna entidad");
     end
rule "Main nodes has exactly one"
    when $a:ProcessIntention(intention().intentType()=="entity")
         $b:MainNode(number==1)
    then
      $a.setAnswer("Se detecto solo una entidad");
     end
rule "There are more thna one"
    when $a:ProcessIntention(intention().intentType()=="entity")
     $b:MainNode(number>1)
    then
      $a.setAnswer("Se detecto mas de un(a) "+$a.category().name());
      $a.concatAnswer();
     end
rule "Intention was not detected"
    when $a:ProcessIntention(intention().intentType()=="")
    then
        $a.setAnswer("No puedo procesar lo que me pides, lo lamento");
     end