package org.vcgdev.supportctxbot

import kie.MessageResponse;
import kie.ProcessIntention
import kie.Customer;
import kie.TicketCreated;
import kie.CommentCreated;
declare MainNode
  number:int
  end
rule "User is asking with no context"
    when $a:ProcessIntention(intention().intentType()=="ask")
    then
        $a.findAnswer();
     end
rule "User has an issue"
    when $a:ProcessIntention(intention().intentType()=="entity")
    then
       $a.searchMainNode();
       MainNode main = new MainNode();
       main.setNumber($a.mainNodes().size());
       insert(main);
     end
rule "There are no main nodes for issue"
    when $b:MainNode(number==0)
        $a:ProcessIntention(intention().intentType()=="entity")
    then
      $a.setAnswer("Se creara un nuevo Ticket para procesar {article} {element}");
     end
rule "Main nodes has exactly one"
    when $a:ProcessIntention(intention().intentType()=="entity")
         $b:MainNode(number==1)
    then
      $a.setAnswer("Se detecto solo una entidad");
     end
rule "There are more thna one"
    when $a:ProcessIntention(intention().intentType()=="entity")
     $b:MainNode(number>1)
    then
      $a.setAnswer("Me puedes decir con que {element} tienes el problema?");
      $a.concatAnswer();
     end
rule "Intention was not detected"
    when $a:ProcessIntention(intention().intentType()=="")
    then
        $a.setAnswer("No puedo procesar lo que me pides, lo lamento");
     end